language: python
python:
  - "3.8"
services:
  - mongodb
install:
  - "pip install pytest"
  - "pip install -r server/requirements.txt"
  - "pip install -r client/requirements.txt"
script: python -m pytest client/tests; python -m pytest server/tests
