version: "3"
services:

  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"

  redis:
    image: 'redis'

  restapi:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/usr/server
    environment:
      - SECRET_KEY=171f8a1082a0b343cb8b0b267c8dab12
      - ROOT_PATH=/usr/server/
      - MONGO_HOST=mongodb
      - DB=iotp
      - UPLOAD_FOLDER=uploads

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/usr/client
    environment:
      - SECRET_KEY=ad204ad0763b81b4868d832ada1b6ba2
      - ROOT_PATH=/usr/client

#  gcapp:
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./gcapp
#    volumes:
#      - ./gcapp:/usr/gcapp
#    environment:
#      - MONGO_HOST=mongodb

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
