version: "3"
services:
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"

  redis:
    image: 'redis'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/usr/app
    environment:
      - SECRET_KEY=171f8a1082a0b343cb8b0b267c8dab12
      - UPLOAD_FOLDER=sketches
      - MONGO_HOST=mongodb
      - DB=iotp

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/usr/app
    environment:
      - SECRET_KEY=171f8a1082a0b343cb8b0b267c8dab12

  gcapp:
    build:
      dockerfile: Dockerfile.dev
      context: ./gcapp
    volumes:
      - ./gcapp:/usr/app
    environment:
      - MONGO_HOST=mongodb
    restart: always

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - "80:80"
