# User an existing docker image as base
FROM python
# Specify work dir path inside the container
WORKDIR /usr/server
# Copy then Download and install depndancies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy project files inside container workdir directory
COPY . .
# Add environment variables
ENV FLASK_ENV=development
ENV FLASK_APP=run
# Tell the image what to do when starts as a container
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
