# User an existing docker image as base
FROM python:3.6
# Specify work dir path inside the container
WORKDIR /usr/gcapp
# Copy then Download and install depndancies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy project files inside container workdir directory
COPY . .
# Tell the image what to do when starts as a container
CMD ["python", "app.py"]
